### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'book_new')

### ISSUE THREAD

**Issue by danis-arslanov** [joaomede/vue3-xlsx#7]
I tryed to use an official example: https://joaomede.github.io/vue3-xlsx/components/js-to-xlsx.html#xlsx-sheet
But I have a mistake in my browser console:
vue3-xlsx.esm.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'book_new')
    at vue3-xlsx.esm.js:1:53020
    at f (jspdf-html2canvas.min.js:1:3229)
    at Generator._invoke (jspdf-html2canvas.min.js:1:2982)
    at Generator.next (jspdf-html2canvas.min.js:1:3588)
    at mn (vue3-xlsx.esm.js:1:20374)
    at a2 (vue3-xlsx.esm.js:1:20579)

The only exception I made:   import {XlsxWorkbook, XlsxSheet} from 'vue3-xlsx';

**Comment by PiusLucky** [comment]
Similar. I have the same issue.  were you able to resolve this @danis-arslanov

**Comment by lukasirsak** [comment]
I am also having this issue.

**Comment by ViacheslavZyrianov** [comment]
Still same issue
